In [34]:
import numpy as np

def multi(x, y):
    return (x + 1) * (y + 1)

a = np.fromfunction(multi, (9, 9))
b = a[0:-1:2, 0:-1:2]
print(b)
a = np.arange(1, 5)
b = a[[1, 2]]
print(b)
b[0] = 3
print(b)
print(a)
c = a[np.array([True, False, False, False])]
print(c)
c[0] = 2
print(a)
c = a[[True, False, True, False]]
print(c)
a[a > 2]
np.arange(0, 60, 10).reshape(-1, 1) + np.arange(0, 6)

[[ 1.  3.  5.  7.]
 [ 3.  9. 15. 21.]
 [ 5. 15. 25. 35.]
 [ 7. 21. 35. 49.]]
[2 3]
[3 3]
[1 2 3 4]
[1]
[1 2 3 4]
[1 3]


array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])